<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>islp3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../https://assets.qiufei.site/personal/profile.jpg" rel="icon" type="image/jpeg">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-681fbf911679f9b3dbf9743eb275ba49.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7e49aeac8059a213a463aa1a739e8272.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://qiufei.github.io"> 
<span class="menu-text">首页</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://qiufei.github.io/web-slide-r"> 
<span class="menu-text">R课件</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://qiufei.github.io/web-slide-marketing"> 
<span class="menu-text">营销课件</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="introduction-to-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-linear-regression">Introduction to Linear Regression</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li>Linear regression is a fundamental approach in supervised learning, used primarily for predicting a quantitative response.</li>
<li>It’s a cornerstone in statistical learning, widely used and extensively studied.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="https://axwslyfy9krb.objectstorage.ap-singapore-1.oci.customer-oci.com/n/axwslyfy9krb/b/qiufei/o/textbook%2Fisl_figures%2F2_1.svg" class="img-fluid"></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Linear regression serves as a stepping stone to more complex statistical learning methods. Many advanced techniques can be seen as extensions or generalizations of linear regression.</p>
</div>
</div>
</div>
</section>
<section id="key-questions-in-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="key-questions-in-linear-regression">Key Questions in Linear Regression</h2>
<p>We explore the <code>Advertising</code> data to address several key questions:</p>
<ol type="1">
<li><strong>Relationship Existence:</strong> Is there a connection between advertising budget and sales?</li>
<li><strong>Relationship Strength:</strong> How strong is the link between budget and sales?</li>
<li><strong>Media Contribution:</strong> Which advertising media (TV, radio, newspaper) contribute to sales?</li>
<li><strong>Association Size:</strong> How much does sales increase for each dollar spent on each medium?</li>
<li><strong>Prediction Accuracy:</strong> Can we accurately predict future sales?</li>
<li><strong>Linearity Check:</strong> Is the relationship between advertising and sales linear?</li>
<li><strong>Media Synergy:</strong> Do the advertising media work together synergistically (interaction effect)?</li>
</ol>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Addressing these questions helps determine if a relationship exists, its strength, individual media contributions, prediction accuracy, the linearity of the connection, and potential synergy effects.</p>
</div>
</div>
</div>
</section>
<section id="simple-linear-regression-the-basics" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-the-basics">Simple Linear Regression: The Basics</h2>
<p>Simple linear regression predicts a quantitative response, <span class="math inline">\(Y\)</span>, using a single predictor variable, <span class="math inline">\(X\)</span>, assuming a linear relationship:</p>
<p><span class="math display">\[
Y \approx \beta_0 + \beta_1X
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: Intercept (value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X = 0\)</span>).</li>
<li><span class="math inline">\(\beta_1\)</span>: Slope (change in <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X\)</span>).</li>
<li><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the model <em>coefficients</em> or <em>parameters</em>.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This equation represents a straight line, where <span class="math inline">\(\beta_0\)</span> is the y-intercept, and <span class="math inline">\(\beta_1\)</span> is the slope.</p>
</div>
</div>
</div>
</section>
<section id="simple-linear-regression-example" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-example">Simple Linear Regression: Example</h2>
<p>For instance, let’s regress <code>sales</code> onto <code>TV</code> advertising:</p>
<p><span class="math display">\[
\text{sales} \approx \beta_0 + \beta_1 \times \text{TV}
\]</span></p>
<ul>
<li><span class="math inline">\(Y\)</span>: Sales (in thousands of units).</li>
<li><span class="math inline">\(X\)</span>: TV advertising budget (in thousands of dollars).</li>
</ul>
<p>Once we estimate the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> (denoted as <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span>), we can predict sales:</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta_0} + \hat{\beta_1}x
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The “hat” symbol (^) indicates an estimated value. <span class="math inline">\(\hat{y}\)</span> is the <em>predicted</em> value of sales.</p>
</div>
</div>
</div>
</section>
<section id="estimating-the-coefficients-least-squares" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-coefficients-least-squares">Estimating the Coefficients: Least Squares</h2>
<p>Our goal is to find <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span> that best fit the data, meaning the line should be as close as possible to the data points <span class="math inline">\((x_i, y_i)\)</span>. We use the <em>least squares</em> method, which minimizes the <em>residual sum of squares</em> (RSS):</p>
<p><span class="math display">\[
\text{RSS} = \sum_{i=1}^{n} (y_i - \hat{y_i})^2 = \sum_{i=1}^{n} (y_i - \hat{\beta_0} - \hat{\beta_1}x_i)^2
\]</span></p>
<ul>
<li><span class="math inline">\(y_i\)</span>: Actual sales for the <span class="math inline">\(i\)</span>-th observation.</li>
<li><span class="math inline">\(\hat{y_i}\)</span>: Predicted sales for the <span class="math inline">\(i\)</span>-th observation.</li>
<li><span class="math inline">\(e_i = y_i - \hat{y_i}\)</span>: The <em>residual</em> for the <span class="math inline">\(i\)</span>-th observation (the difference between the actual and predicted values).</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Least squares finds the line that minimizes the sum of the squared vertical distances between the data points and the line.</p>
</div>
</div>
</div>
</section>
<section id="estimating-the-coefficients-formulas" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-coefficients-formulas">Estimating the Coefficients: Formulas</h2>
<p>Using calculus, we find the values of <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span> that minimize RSS:</p>
<p><span class="math display">\[
\hat{\beta_1} = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})^2}
\]</span></p>
<p><span class="math display">\[
\hat{\beta_0} = \bar{y} - \hat{\beta_1}\bar{x}
\]</span></p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span>: Sample mean of <span class="math inline">\(X\)</span>.</li>
<li><span class="math inline">\(\bar{y}\)</span>: Sample mean of <span class="math inline">\(Y\)</span>.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>These formulas provide the best estimates for the slope and intercept based on the available data. The slope (<span class="math inline">\(\hat{\beta_1}\)</span>) represents the average change in Y for a one-unit increase in X, and the intercept (<span class="math inline">\(\hat{\beta_0}\)</span>) is the predicted value of Y when X is zero.</p>
</div>
</div>
</div>
</section>
<section id="visualizing-the-least-squares-fit" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-least-squares-fit">Visualizing the Least Squares Fit</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://axwslyfy9krb.objectstorage.ap-singapore-1.oci.customer-oci.com/n/axwslyfy9krb/b/qiufei/o/textbook%2Fisl_figures%2F3_1.svg" class="img-fluid figure-img"></p>
<figcaption>Least Squares Fit</figcaption>
</figure>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This figure shows the least squares regression line for <code>sales</code> versus <code>TV</code> advertising. Each grey line segment represents a <em>residual</em>, the difference between the observed <code>sales</code> value and the value predicted by the line. The least squares method minimizes the sum of the squares of these residuals.</p>
</div>
</div>
</div>
</section>
<section id="assessing-coefficient-accuracy-population-vs.-sample" class="level2">
<h2 class="anchored" data-anchor-id="assessing-coefficient-accuracy-population-vs.-sample">Assessing Coefficient Accuracy: Population vs.&nbsp;Sample</h2>
<ul>
<li><strong>Population Regression Line:</strong> The “true” (but usually unknown) relationship: <span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>.</li>
<li><strong>Least Squares Line:</strong> The estimated relationship based on our sample: <span class="math inline">\(\hat{y} = \hat{\beta_0} + \hat{\beta_1}x\)</span>.</li>
<li><span class="math inline">\(\epsilon\)</span>: random error term</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://axwslyfy9krb.objectstorage.ap-singapore-1.oci.customer-oci.com/n/axwslyfy9krb/b/qiufei/o/textbook%2Fisl_figures%2F3_3.svg" class="img-fluid figure-img"></p>
<figcaption>Population vs.&nbsp;Sample Regression Lines</figcaption>
</figure>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The left panel shows the true population regression line (red) and the estimated least squares line (blue) from a single sample. The right panel shows ten different least squares lines, each estimated from a different sample drawn from the same population. The least squares lines vary, but they cluster around the true population line.</p>
</div>
</div>
</div>
</section>
<section id="assessing-coefficient-accuracy-unbiasedness" class="level2">
<h2 class="anchored" data-anchor-id="assessing-coefficient-accuracy-unbiasedness">Assessing Coefficient Accuracy: Unbiasedness</h2>
<ul>
<li><span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span> are <em>estimates</em> of the true (unknown) parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</li>
<li>These estimates are <em>unbiased</em>: on average, they will equal the true values. This means if we took many samples and calculated the estimates each time, the average of the estimates would converge to the true values.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Unbiasedness means that our estimation method doesn’t systematically over- or underestimate the true values.</p>
</div>
</div>
</div>
</section>
<section id="assessing-coefficient-accuracy-standard-error" class="level2">
<h2 class="anchored" data-anchor-id="assessing-coefficient-accuracy-standard-error">Assessing Coefficient Accuracy: Standard Error</h2>
<ul>
<li><strong>Standard Error:</strong> Measures the average amount that an estimate (<span class="math inline">\(\hat{\beta_0}\)</span> or <span class="math inline">\(\hat{\beta_1}\)</span>) differs from the true value (<span class="math inline">\(\beta_0\)</span> or <span class="math inline">\(\beta_1\)</span>).</li>
<li>Formulas for standard errors:</li>
</ul>
<p><span class="math display">\[
\text{SE}(\hat{\beta_0})^2 = \sigma^2 \left[ \frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^{n}(x_i - \bar{x})^2} \right]
\]</span></p>
<p><span class="math display">\[
\text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^{n}(x_i - \bar{x})^2}
\]</span> - <span class="math inline">\(\sigma^2\)</span>: Variance of the error term <span class="math inline">\(\epsilon\)</span> (usually unknown, estimated by the <em>residual standard error</em>, RSE).</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Smaller standard errors indicate more precise estimates. Notice that SE(<span class="math inline">\(\hat{\beta_1}\)</span>) is smaller when the <span class="math inline">\(x_i\)</span> values are more spread out.</p>
</div>
</div>
</div>
</section>
<section id="assessing-coefficient-accuracy-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="assessing-coefficient-accuracy-confidence-intervals">Assessing Coefficient Accuracy: Confidence Intervals</h2>
<ul>
<li><strong>Confidence Interval:</strong> A range of values that is likely to contain the true unknown value of a parameter, with a certain level of confidence (e.g., 95%).</li>
<li>Approximate 95% confidence interval for <span class="math inline">\(\beta_1\)</span>:</li>
</ul>
<p><span class="math display">\[
\hat{\beta_1} \pm 2 \cdot \text{SE}(\hat{\beta_1})
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This means that if we were to repeatedly sample from the population and construct 95% confidence intervals, approximately 95% of those intervals would contain the true value of <span class="math inline">\(\beta_1\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<ul>
<li><strong>Null Hypothesis (H₀):</strong> There is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> (<span class="math inline">\(\beta_1 = 0\)</span>).</li>
<li><strong>Alternative Hypothesis (Hₐ):</strong> There is <em>some</em> relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> (<span class="math inline">\(\beta_1 \neq 0\)</span>).</li>
<li><strong>t-statistic:</strong> Measures how many standard deviations <span class="math inline">\(\hat{\beta_1}\)</span> is away from 0:</li>
</ul>
<p><span class="math display">\[
t = \frac{\hat{\beta_1} - 0}{\text{SE}(\hat{\beta_1})}
\]</span></p>
<ul>
<li><strong>p-value:</strong> The probability of observing a t-statistic as extreme as, or more extreme than, the one calculated, <em>assuming</em> <span class="math inline">\(H_0\)</span> is true.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>A small p-value (typically &lt; 0.05) provides evidence <em>against</em> the null hypothesis, suggesting a relationship between X and Y.</p>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing-example-advertising-data" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing-example-advertising-data">Hypothesis Testing: Example (Advertising Data)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Coefficient</th>
<th style="text-align: left;">Std. error</th>
<th style="text-align: left;">t-statistic</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">7.0325</td>
<td style="text-align: left;">0.4578</td>
<td style="text-align: left;">15.36</td>
<td style="text-align: left;">&lt; 0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">TV</td>
<td style="text-align: left;">0.0475</td>
<td style="text-align: left;">0.0027</td>
<td style="text-align: left;">17.67</td>
<td style="text-align: left;">&lt; 0.0001</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The table shows the results of regressing <code>sales</code> on <code>TV</code> advertising. The very small p-value for <code>TV</code> provides strong evidence that <span class="math inline">\(\beta_1 \neq 0\)</span>, meaning there <em>is</em> a relationship between TV advertising and sales.</p>
</div>
</div>
</div>
</section>
<section id="assessing-model-accuracy-rse" class="level2">
<h2 class="anchored" data-anchor-id="assessing-model-accuracy-rse">Assessing Model Accuracy: RSE</h2>
<ul>
<li><strong>Residual Standard Error (RSE):</strong> An estimate of the standard deviation of the error term <span class="math inline">\(\epsilon\)</span>. It represents the average amount that the response will deviate from the true regression line.</li>
</ul>
<p><span class="math display">\[
\text{RSE} = \sqrt{\frac{1}{n-2}\text{RSS}} = \sqrt{\frac{1}{n-2}\sum_{i=1}^{n}(y_i - \hat{y_i})^2}
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Lower RSE values indicate a better fit. The RSE is measured in the units of Y.</p>
</div>
</div>
</div>
</section>
<section id="assessing-model-accuracy-r²" class="level2">
<h2 class="anchored" data-anchor-id="assessing-model-accuracy-r²">Assessing Model Accuracy: R²</h2>
<ul>
<li><strong>R² Statistic:</strong> Measures the <em>proportion of variance explained</em> by the model. It always falls between 0 and 1.</li>
</ul>
<p><span class="math display">\[
R^2 = \frac{\text{TSS} - \text{RSS}}{\text{TSS}} = 1 - \frac{\text{RSS}}{\text{TSS}}
\]</span></p>
<ul>
<li><strong>Total Sum of Squares (TSS):</strong> <span class="math inline">\(\sum(y_i - \bar{y})^2\)</span> - Measures the total variance in the response <span class="math inline">\(Y\)</span>.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>R² closer to 1 indicates that a large proportion of the variability in the response is explained by the regression. R² is the square of the correlation between X and Y in simple linear regression.</p>
</div>
</div>
</div>
</section>
<section id="assessing-model-accuracy-example-advertising-data" class="level2">
<h2 class="anchored" data-anchor-id="assessing-model-accuracy-example-advertising-data">Assessing Model Accuracy: Example (Advertising Data)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Residual standard error</td>
<td style="text-align: left;">3.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">R²</td>
<td style="text-align: left;">0.612</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F-statistic</td>
<td style="text-align: left;">312.1</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>For the regression of <code>sales</code> on <code>TV</code>, the RSE is 3.26 (thousands of units), and the R² is 0.612. This means that about 61.2% of the variability in sales is explained by TV advertising.</p>
</div>
</div>
</div>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h2>
<p>Extends simple linear regression to handle <em>multiple</em> predictors:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \dots + \beta_pX_p + \epsilon
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_j\)</span>: The average effect on <span class="math inline">\(Y\)</span> of a one-unit increase in <span class="math inline">\(X_j\)</span>, <em>holding all other predictors fixed</em>.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Each predictor now has its own slope coefficient.</p>
</div>
</div>
</div>
</section>
<section id="multiple-linear-regression-example-advertising-data" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-example-advertising-data">Multiple Linear Regression: Example (Advertising Data)</h2>
<p><span class="math display">\[
\text{sales} = \beta_0 + \beta_1 \times \text{TV} + \beta_2 \times \text{radio} + \beta_3 \times \text{newspaper} + \epsilon
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: left;">Coefficient</th>
<th style="text-align: left;">Std. error</th>
<th style="text-align: left;">t-statistic</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">2.939</td>
<td style="text-align: left;">0.3119</td>
<td style="text-align: left;">9.42</td>
<td style="text-align: left;">&lt; 0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">TV</td>
<td style="text-align: left;">0.046</td>
<td style="text-align: left;">0.0014</td>
<td style="text-align: left;">32.81</td>
<td style="text-align: left;">&lt; 0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">radio</td>
<td style="text-align: left;">0.189</td>
<td style="text-align: left;">0.0086</td>
<td style="text-align: left;">21.89</td>
<td style="text-align: left;">&lt; 0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">newspaper</td>
<td style="text-align: left;">-0.001</td>
<td style="text-align: left;">0.0059</td>
<td style="text-align: left;">-0.18</td>
<td style="text-align: left;">0.8599</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Holding TV and newspaper advertising fixed, spending an additional $1,000 on radio advertising is associated with an increase in sales of approximately 189 units. The newspaper coefficient is not statistically significant. The interpretation changes compared to simple linear regression due to correlations between the predictors.</p>
</div>
</div>
</div>
</section>
<section id="correlation-between-predictors" class="level2">
<h2 class="anchored" data-anchor-id="correlation-between-predictors">Correlation Between Predictors</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">TV</th>
<th style="text-align: left;">radio</th>
<th style="text-align: left;">newspaper</th>
<th style="text-align: left;">sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TV</td>
<td style="text-align: left;">1.0000</td>
<td style="text-align: left;">0.0548</td>
<td style="text-align: left;">0.0567</td>
<td style="text-align: left;">0.7822</td>
</tr>
<tr class="even">
<td style="text-align: left;">radio</td>
<td style="text-align: left;">0.0548</td>
<td style="text-align: left;">1.0000</td>
<td style="text-align: left;">0.3541</td>
<td style="text-align: left;">0.5762</td>
</tr>
<tr class="odd">
<td style="text-align: left;">newspaper</td>
<td style="text-align: left;">0.0567</td>
<td style="text-align: left;">0.3541</td>
<td style="text-align: left;">1.0000</td>
<td style="text-align: left;">0.2283</td>
</tr>
<tr class="even">
<td style="text-align: left;">sales</td>
<td style="text-align: left;">0.7822</td>
<td style="text-align: left;">0.5762</td>
<td style="text-align: left;">0.2283</td>
<td style="text-align: left;">1.0000</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This correlation matrix shows the pairwise correlations between the variables in the <code>Advertising</code> data. Notice the moderate correlation (0.35) between <code>radio</code> and <code>newspaper</code>. This explains the difference in the <code>newspaper</code> coefficient between the simple and multiple linear regressions.</p>
</div>
</div>
</div>
</section>
<section id="important-questions-in-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="important-questions-in-multiple-linear-regression">Important Questions in Multiple Linear Regression</h2>
<ol type="1">
<li><strong>Any Useful Predictors?</strong> Is at least <em>one</em> predictor useful in predicting the response? (F-test)</li>
<li><strong>All or Subset?</strong> Do <em>all</em> predictors help explain <span class="math inline">\(Y\)</span>, or only a subset? (Variable selection)</li>
<li><strong>Model Fit:</strong> How well does the model fit the data? (RSE, R²)</li>
<li><strong>Prediction:</strong> Given predictor values, what should we predict for the response, and how accurate is our prediction? (Prediction intervals, confidence intervals)</li>
</ol>
</section>
<section id="one-is-there-a-relationship-f-test" class="level2">
<h2 class="anchored" data-anchor-id="one-is-there-a-relationship-f-test">One: Is There a Relationship? (F-test)</h2>
<ul>
<li><strong>Null Hypothesis (H₀):</strong> <em>All</em> coefficients are zero (<span class="math inline">\(\beta_1 = \beta_2 = \dots = \beta_p = 0\)</span>).</li>
<li><strong>Alternative Hypothesis (Hₐ):</strong> At least <em>one</em> coefficient is non-zero.</li>
<li><strong>F-statistic:</strong></li>
</ul>
<p><span class="math display">\[
F = \frac{(\text{TSS} - \text{RSS})/p}{\text{RSS}/(n - p - 1)}
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>If there’s <em>no</em> relationship between the response and predictors, the F-statistic will be close to 1. If Hₐ is true, F will be <em>greater</em> than 1.</p>
</div>
</div>
</div>
</section>
<section id="f-test-example-advertising-data" class="level2">
<h2 class="anchored" data-anchor-id="f-test-example-advertising-data">F-test: Example (Advertising Data)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Residual standard error</td>
<td style="text-align: left;">1.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">R²</td>
<td style="text-align: left;">0.897</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F-statistic</td>
<td style="text-align: left;">570</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>The F-statistic for the multiple regression of <code>sales</code> on <code>TV</code>, <code>radio</code>, and <code>newspaper</code> is 570. This is much larger than 1, providing strong evidence against the null hypothesis. The p-value is essentially zero, indicating that at least one advertising medium is related to sales.</p>
</div>
</div>
</div>
</section>
<section id="two-deciding-on-important-variables-variable-selection" class="level2">
<h2 class="anchored" data-anchor-id="two-deciding-on-important-variables-variable-selection">Two: Deciding on Important Variables (Variable Selection)</h2>
<ul>
<li><strong>Goal:</strong> Identify the subset of predictors that are most strongly related to the response.</li>
<li><strong>Methods:</strong>
<ul>
<li><em>Forward Selection:</em> Start with the null model (intercept only) and add predictors one by one.</li>
<li><em>Backward Selection:</em> Start with all predictors and remove them one by one.</li>
<li><em>Mixed Selection:</em> Combination of forward and backward selection.</li>
</ul></li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>We typically can’t try all possible subsets of predictors (there are 2ᵖ of them!), so we use these more efficient methods.</p>
</div>
</div>
</div>
</section>
<section id="three-model-fit-rse-and-r²" class="level2">
<h2 class="anchored" data-anchor-id="three-model-fit-rse-and-r²">Three: Model Fit (RSE and R²)</h2>
<ul>
<li><strong>RSE and R²:</strong> Same interpretations as in simple linear regression.</li>
<li><strong>Important Note:</strong> R² will <em>always</em> increase when more variables are added to the model, even if those variables are only weakly associated with the response.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Adding more variables always reduces the RSS on the <em>training</em> data, but may not improve predictions on <em>new</em> data.</p>
</div>
</div>
</div>
</section>
<section id="four-predictions" class="level2">
<h2 class="anchored" data-anchor-id="four-predictions">Four: Predictions</h2>
<p>Three sources of uncertainty in predictions:</p>
<ol type="1">
<li><strong>Coefficient Uncertainty:</strong> The least squares plane is only an <em>estimate</em> of the true population regression plane. (Reducible error, addressed with confidence intervals)</li>
<li><strong>Model Bias:</strong> The linear model is likely an approximation. (Reducible error, addressed by considering more complex models)</li>
<li><strong>Irreducible Error:</strong> Even if we knew the true relationship, we couldn’t predict <span class="math inline">\(Y\)</span> perfectly because of the random error <span class="math inline">\(\epsilon\)</span>. (Addressed with prediction intervals)</li>
</ol>
</section>
<section id="confidence-vs.-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-vs.-prediction-intervals">Confidence vs.&nbsp;Prediction Intervals</h2>
<ul>
<li><strong>Confidence Interval:</strong> Quantifies uncertainty around the <em>average</em> response value.</li>
<li><strong>Prediction Interval:</strong> Quantifies uncertainty around a <em>single</em> response value.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Prediction intervals are <em>always</em> wider than confidence intervals because they account for both the uncertainty in estimating the population regression plane <em>and</em> the inherent variability of individual data points around that plane.</p>
</div>
</div>
</div>
</section>
<section id="qualitative-predictors" class="level2">
<h2 class="anchored" data-anchor-id="qualitative-predictors">Qualitative Predictors</h2>
<ul>
<li><strong>Qualitative Predictor (Factor):</strong> A variable with categorical values (levels).</li>
<li><strong>Dummy Variable:</strong> A numerical variable used to represent a qualitative predictor in a regression model.
<ul>
<li>For a predictor with two levels: Create one dummy variable.</li>
<li>For a predictor with more than two levels: Create one fewer dummy variable than the number of levels.</li>
<li>One level will serve as a baseline.</li>
</ul></li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<pre><code>Each dummy variable is coded as 0 or 1, indicating the absence or presence of a particular level.</code></pre>
</div>
</div>
</div>
</section>
<section id="qualitative-predictors-example-credit-data" class="level2">
<h2 class="anchored" data-anchor-id="qualitative-predictors-example-credit-data">Qualitative Predictors: Example (Credit Data)</h2>
<p>We want to predict <code>balance</code> using the <code>own</code> variable (whether someone owns a house).</p>
<ul>
<li>Create a dummy variable:</li>
</ul>
<p><span class="math display">\[
x_i = \begin{cases}
1 &amp; \text{if person } i \text{ owns a house} \\
0 &amp; \text{if person } i \text{ does not own a house}
\end{cases}
\]</span></p>
<ul>
<li>Regression model:</li>
</ul>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1x_i + \epsilon_i = \begin{cases}
\beta_0 + \beta_1 + \epsilon_i &amp; \text{if person } i \text{ owns a house} \\
\beta_0 + \epsilon_i &amp; \text{if person } i \text{ does not own a house}
\end{cases}
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><span class="math inline">\(\beta_0\)</span> represents the average credit card balance for non-owners, and <span class="math inline">\(\beta_0 + \beta_1\)</span> represents the average balance for owners. <span class="math inline">\(\beta_1\)</span> is the average <em>difference</em> in balance between owners and non-owners.</p>
</div>
</div>
</div>
</section>
<section id="interactions" class="level2">
<h2 class="anchored" data-anchor-id="interactions">Interactions</h2>
<ul>
<li><strong>Additive Assumption:</strong> The effect of one predictor on the response does <em>not</em> depend on the values of other predictors.</li>
<li><strong>Interaction Effect (Synergy):</strong> The effect of one predictor on the response <em>does</em> depend on the values of other predictors.</li>
<li><strong>Interaction Term:</strong> Include the <em>product</em> of two predictors in the model.</li>
</ul>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Interactions allow the relationship between a predictor and the response to vary depending on the values of other predictors.</p>
</div>
</div>
</div>
</section>
<section id="interactions-example-advertising-data" class="level2">
<h2 class="anchored" data-anchor-id="interactions-example-advertising-data">Interactions: Example (Advertising Data)</h2>
<p><span class="math display">\[
\text{sales} = \beta_0 + \beta_1 \times \text{TV} + \beta_2 \times \text{radio} + \beta_3 \times (\text{TV} \times \text{radio}) + \epsilon
\]</span></p>
<p>This can be rewritten as:</p>
<p><span class="math display">\[
\text{sales} = \beta_0 + (\beta_1 + \beta_3 \times \text{radio}) \times \text{TV} + \beta_2 \times \text{radio} + \epsilon
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Now, the slope for <code>TV</code> depends on the value of <code>radio</code>. The interaction term allows for synergy between the advertising media.</p>
</div>
</div>
</div>
</section>
<section id="non-linear-relationships-polynomial-regression" class="level2">
<h2 class="anchored" data-anchor-id="non-linear-relationships-polynomial-regression">Non-linear Relationships: Polynomial Regression</h2>
<ul>
<li><strong>Linearity Assumption:</strong> The relationship between the predictors and the response is linear.</li>
<li><strong>Polynomial Regression:</strong> Include polynomial terms (e.g., <span class="math inline">\(X^2\)</span>, <span class="math inline">\(X^3\)</span>) of the predictors in the model to capture non-linear relationships.</li>
</ul>
<p><span class="math display">\[
\text{mpg} = \beta_0 + \beta_1 \times \text{horsepower} + \beta_2 \times \text{horsepower}^2 + \epsilon
\]</span></p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This is still a <em>linear</em> regression model (linear in the coefficients), but it models a <em>non-linear</em> relationship between <code>mpg</code> and <code>horsepower</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://axwslyfy9krb.objectstorage.ap-singapore-1.oci.customer-oci.com/n/axwslyfy9krb/b/qiufei/o/textbook%2Fisl_figures%2F3_8.svg" class="img-fluid figure-img"></p>
<figcaption>Polynomial Regression</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="potential-problems-in-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="potential-problems-in-linear-regression">Potential Problems in Linear Regression</h2>
<ol type="1">
<li><strong>Non-linearity:</strong> The relationship between response and predictors is not linear. (Use residual plots to detect)</li>
<li><strong>Correlation of Error Terms:</strong> Errors are not independent. (Common in time series data)</li>
<li><strong>Non-constant Variance of Error Terms (Heteroscedasticity):</strong> Variance of errors changes with the response. (Funnel shape in residual plot)</li>
<li><strong>Outliers:</strong> Observations with unusual response values.</li>
<li><strong>High Leverage Points:</strong> Observations with unusual predictor values.</li>
<li><strong>Collinearity:</strong> Predictors are highly correlated.</li>
</ol>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>These problems can affect the accuracy and interpretability of the regression model.</p>
</div>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li>Linear regression is a fundamental and versatile tool for predicting a quantitative response.</li>
<li>It relies on assumptions about linearity, additivity, and the error terms.</li>
<li>We can assess model fit using RSE and R², and assess coefficient significance using t-statistics and p-values.</li>
<li>Multiple linear regression allows for multiple predictors, and we can use the F-test to check for any relationship between the predictors and the response.</li>
<li>Extensions like qualitative predictors, interaction terms, and polynomial regression increase the flexibility of the linear model.</li>
</ul>
</section>
<section id="thoughts-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="thoughts-and-discussion">Thoughts and Discussion</h2>
<ul>
<li>How do we choose the “best” model among a set of possible models (e.g., different combinations of predictors, interactions, polynomial terms)?</li>
<li>What are the limitations of linear regression, and when might other, more complex methods be more appropriate?</li>
<li>How can we effectively diagnose and address the potential problems in linear regression (non-linearity, collinearity, etc.)?</li>
<li>How can the insights from a linear regression model be used to inform real-world decisions (e.g., marketing strategies)?</li>
<li>How does the size and quality of data affect the model outcome?</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/qiufei\.github\.io\/web-slide-r");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>🔋<a href="https://posit.co"><img src="https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg" class="img-fluid" alt="Posit" width="65"></a></p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 邱飞 © 2025
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://beian.miit.gov.cn">
<p>浙ICP备 2024072710号-1</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511">
<p>浙公网安备 33021202002511号</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:hfutqiufei@163.com">
      <i class="bi bi-envelope-at-fill" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>